name = "Re-Console: Legacy TU5"
author = "ViolaFlower Modding"
version = "0.0.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7697512324eee760efb867a512bc8322d8309b4cc6187d716b53a9d53f0dfd70"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
