name = "Re-Console: Legacy TU1"
author = "ViolaFlower Modding"
version = "0.0.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da804280fd8ef0ae6cbcd21611717f2697d18f1f09376914f7d0e79c8318dce0"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
