name: Dev Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-devs:
    runs-on: ubuntu-latest
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACK_NAME: Re-Console-Legacy
      OUTPUT: artifacts
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest

    - name: Create short commit SHA
      id: vars
      run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV

    - name: Prepare builds
      run: |
          cp ./LICENSE ./versions/TU1/
          cp ./README.md ./versions/TU1/

          cp ./LICENSE ./versions/TU3/
          cp ./README.md ./versions/TU3/

          cp ./LICENSE ./versions/TU5/
          cp ./README.md ./versions/TU5/

    - name: Create TU1 build
      run: |
          cd ./versions/TU1/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-TU1-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Create TU3 build
      run: |
          cd ./versions/TU3/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-TU3-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Create TU5 build
      run: |
          cd ./versions/TU5/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-TU5-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Prepare artifacts
      run: |
          mkdir $OUTPUT
          
          mv ./versions/TU1/${PACK_NAME}-TU1-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/
          mv ./versions/TU3/${PACK_NAME}-TU3-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/
          mv ./versions/TU5/${PACK_NAME}-TU5-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Re-Console-Legacy-dev-${{ env.COMMIT_SHORT_SHA }}"
        path: artifacts
