name: Dev Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-devs:
    runs-on: ubuntu-latest
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACK_NAME: Re-Console-Legacy
      OUTPUT: artifacts
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest

    - name: Create short commit SHA
      id: vars
      run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV

    - name: Prepare builds
      run: |
          mkdir TU1-temp
          cp -r ./versions/Common/* ./TU1-temp/
          cp -r ./versions/TU1/* ./TU1-temp/
          cp ./LICENSE.md ./TU1-temp/
          cp ./README.md ./TU1-temp/

          mkdir TU3-temp
          cp -r ./versions/Common/* ./TU3-temp/
          cp -r ./versions/TU3/* ./TU3-temp/
          cp ./LICENSE.md ./TU3-temp/
          cp ./README.md ./TU3-temp/

          mkdir TU5-temp
          cp -r ./versions/Common/* ./TU5-temp/
          cp -r ./versions/TU5/* ./TU5-temp/
          cp ./LICENSE.md ./TU5-temp/
          cp ./README.md ./TU5-temp/

    - name: Create TU1 build
      run: |
          cd ./TU1-temp/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-TU1-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Create TU3 build
      run: |
          cd ./TU3-temp/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-TU3-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Create TU5 build
      run: |
          cd ./TU5-temp/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-TU5-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Prepare artifacts
      run: |
          mkdir $OUTPUT
          
          mv ./TU1-temp/${PACK_NAME}-TU1-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/
          mv ./TU3-temp/${PACK_NAME}-TU3-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/
          mv ./TU5-temp/${PACK_NAME}-TU5-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Re-Console-Legacy-dev-${{ env.COMMIT_SHORT_SHA }}"
        path: artifacts
